# Site settings
title: 西蒙宫的博客
description: I think, therefore I am.
disqus_shortname: simongong
url:              //gj3169.github.io, http://blog.simongong.net/
twitter_username: simon_gong
github_username:  gj3169
##########################
owner:
  name:           西蒙宫
  avatar:         avatar.jpg
  bio:            "I think, therefore I am."
  email:          ximenggong@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        simon_gong
  facebook:       
  github:         gj3169
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +yourid

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-70866141-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
################################
