# Site settings
title: 西蒙宫的博客
email: ximenggong@outlook.com
<<<<<<< HEAD
description: I think, therefore I am.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.simongong.net/" # the base hostname & protocol for your site
twitter_username: simon_gong
github_username:  gj3169

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 西蒙宫
  email: ximenggong@outlook.com
  link: http://blog.simongong.net/
  weibo: http://weibo.com/kiteoftime
  github: http://github.com/gj3169
title: 西蒙宫的博客                            #自定义常量

# avatar头像及Favicon
avatar: http://7xind4.com1.z0.glb.clouddn.com/jekyllfavicon.ico
favicon: http://7xind4.com1.z0.glb.clouddn.com/jekyllfavicon.ico
#https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器

# google analytics 设置
ga:
  id: UA-70441296-1
  url: auto
#

# disqus 设置
disqus:
  shortname: simongong
=======
description: 编程爱好者，兴趣广泛
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  gj3169
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
>>>>>>> 801dda2e9226335e7ae5589150473c116b8d2412
